Cargo.toml: bump msrv to 1.83
1.82 fails to build with
```
error[E0658]: use of unstable library feature 'io_error_more'
  --> src/main.rs:74:35
   |
74 |             Err(e) if e.kind() == std::io::ErrorKind::NotADirectory => {
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #86442 <https://github.com/rust-lang/rust/issues/86442> for more information

For more information about this error, try `rustc --explain E0658`.
```

and previous versions had even other error.
This is good enough for debian trixie, so that'll do...